### ISSUE TITLE
Logging messages

### ISSUE THREAD

**Issue by ze42** [nbs-system/snuffleupagus#1]
Last I've checked, error messages are misleading between simulation mode, and blocking mode.

The error messages are the same, and do not discriminate between both.

* Simulation should have a prefix/suffix/something that clearly state it was not actualy blocked.
and/or
* Blocking mode should clearly state so, with a part that is NOT present in simulation mode.

**Comment by wargio** [comment]
fixed by https://github.com/nbs-system/snuffleupagus/commit/b90e0ecc6b0717786ae72236c37157f1b5983521
