### ISSUE TITLE
build error on FreeBSD 11

### ISSUE THREAD

**Issue by fichtner** [nbs-system/snuffleupagus#100]
Hi,

First of all congrats to 0.1.0 and thank you for making that happen!  :)

A FreeBSD port was created today:

https://svnweb.freebsd.org/ports?view=revision&revision=457156

There is one slight issue in the build addressed by:

https://svnweb.freebsd.org/ports/head/security/snuffleupagus/files/patch-sp__network__utils.c?view=markup&pathrev=457156

It seems that *s6_addr32* is simply not provided to userspace in FreeBSD and may need an if-else guard or similar like currently commented out. Or it could be defined if not already defined by the userspace?

Cheers,
Franco

**Comment by jvoisin** [comment]
Thank you very much for trying to join the party!

Apparently, `s6_addr` should be portable, can you please try to remove the trailing `32` and see what happens?

Thank you ♥

**Comment by fichtner** [comment]
@jvoisin thanks, that fix looks good. I'll have some more things to do before circling back to testing in January. We plan to integrate the extension into OPNsense some time in 2018. We used to have Suhoshin, but subsequently PHP 7 happened and I'm sure you know the rest. :)

Cheers,
Franco
