### ISSUE TITLE
Shall we deploy rules files in the packages?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#101]
Since we didn't manage to internally reach an acceptable consensus about this, we're asking the community: There are currently no well accepted usage with regard to where to place non-`.ini` files for php, since every other module is using `.ini`. Snuffleupagus is *special*, as it uses `.rules` ones. So the question is:

Shall we place the `default.rules` files on the filesystem during the installation of the packages, and if yes, where?

@fichtner, @fr33tux, … any opinion about this?

**Comment by Yoda-BZH** [comment]
In Debian:
The package may provide example rules in /usr/share/snufflepagus/examples/
A main config files should be in /etc/snufflepages/
several additional rules may be put in /etc/snufflepages/rules.d/

**Comment by jvoisin** [comment]
Solved for now in our Debian package by 60888daa7fb433ca15157256980f8baeb8b698a0
