### ISSUE TITLE
How much granularity do we want for our eval black/whitelist?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#118]
Do we want to match on:
- method names, or do we want something like `class:method` instead? The later is slower, and I don't think that it might be remotely useful.
- file names, like allowing per file matches. This could allow fancy things like virtual-patching everything in a big file, with different `eval`-rules, but I don't think that this usecase will be really popular.

**Comment by buixor** [comment]
imho, having `.filename()` support is a must-have for virtual patching, `class:method` is less useful.

**Comment by buixor** [comment]
after second thought it seems not-that-easy to implement, thus I guess the feature seems ok for now. Experience will tell us how much of a needed feature this is ;)

**Comment by jvoisin** [comment]
Nobody complained, so I guess we can close it :)
