### ISSUE TITLE
Do we want to mitigate injections inside create_function à la eval?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#119]
While [create_function](https://github.com/rapid7/metasploit-framework/issues/8630) is deprecated, it can still be used in PHP7. Do we want to mitigate injections in it, à la `eval`, or do we consider that since it's both deprecated and not that widespread, we can just ignore it?

**Comment by AndreyNazarchuk** [comment]
can an option be added to disable it?

**Comment by jvoisin** [comment]
If it's implemented, sure: everything is toggleable in Snuffleupagus :)

**Comment by jvoisin** [comment]
We can just ignore it in my opinion.
