### ISSUE TITLE
sp.configuration_file

### ISSUE THREAD

**Issue by remicollet** [nbs-system/snuffleupagus#125]
From configuration documentation

> Since PHP ini-like configuration model isn’t flexible enough, Snuffleupagus is using its own format in the file specified by the directive sp.configuration_file (in your php.ini file), like sp.configuration_file=/etc/php/conf.d/snuffleupagus.ini.
> 
> You can use the , separator to include multiple configuration files : sp.configuration_file=/etc/php/conf.d/snuffleupagus.ini,/etc/php/conf.d/sp_wordpress.ini
> 

As explained, this not a ini file, so don't use .ini in the name.

`sp.configuration_file=/etc/php.d/snuffleupagus.conf`

Will be nice to have glob support, so 

`sp.configuration_file=/etc/php.d/snuffleupagus*.conf`

E.g. having `/etc/php.d/snuffleupagus-default.conf` and `/etc/php.d/snuffleupagus-wordpress.conf`

**Comment by remicollet** [comment]
So in short, as already used for  

`opcache.blacklist_filename=/etc/php.d/opcache*.blacklist`

**Comment by jvoisin** [comment]
I fixed the documentation in c473be13687ebd98c328f390d936be311dae7db6

@blotus will implemented the glob support.
