### ISSUE TITLE
Support match on calltrace for the `ret` filter

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#144]
Currently, it's not possible to match on a calltrace with the `ret` filter. A naive copy/pasta yield an infinite loop, because `execute_data->prev_execute_data->prev_execute_data->prev_execute_data-> …` is looping after some time here, apparently in `Composer\Autoload\ClassLoader::loadClass`.

This can't be reproduced with the current testsuite only in Joomla :/

**Comment by kkadosh** [comment]
This issue is related to #144 .
