### ISSUE TITLE
Make sure that every option supports .dump()

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#147]
Currently, the `.dump()` filter is only supported on filters, not on options. It would be great to implement it for single one:

- [x] unserialize
- [ ] eval black/white list
- [ ] execution of writable PHP files?

**Comment by kkadosh** [comment]
I'm taking this issue, starting with unserialize.
This is how i will proceed : 

 1. Making sure that the configuration parser for unserialize accepts `.dump()`
2. Actually implement the dump feature for unserialize

Is there a better way?

**Comment by jvoisin** [comment]
Wonderful ♥
