### ISSUE TITLE
Adding extra info in disabled_functions log for analysis

### ISSUE THREAD

**Issue by chmodxxx** [nbs-system/snuffleupagus#151]
Can we add extra infos on the drop log of `disabled_functions`, like what are the args of the dropped function, it can be nice to see what the user was looking for.

**Comment by jvoisin** [comment]
You can already use the `.dump` filter to get a complete dump of the request.

I'm not sure that we want to display all the arguments from the function in the logs. We're already displaying the one that matched a specific rule anyway.

**Comment by jvoisin** [comment]
It seems that the core team does think that this is already covered by `.dump()` :)
