### ISSUE TITLE
Changing the name of this project just became a TOP PRIORITY feature to implement IMHO

### ISSUE THREAD

**Issue by cbrocas** [nbs-system/snuffleupagus#180]
Hi Ju and friends!
As a conference organizer you are going to come to speak about this project, I had to deal with this f***ing name far more than I would ever wanted to!
Please be kind with your users, just drop this Sn{ufleupags}* horror name and choose something short, pronounceable and user convenient :)
Thanks for preserving the infosec community health :D 
Cheers, Christophe

**Comment by cbrocas** [comment]
Yes I am kidding but ... if you think it is possible from your point of view, just go ahead and I will buy the first beer to all the members of the core team! :P

**Comment by jvoisin** [comment]
I'll be happy to:

1. buy **you** a beer at [pass the salt]( https://2018.pass-the-salt.org/ );
2. explain on stage in great details why we chose this specific name;
3. Update and close this issue with the slides after the talk

Does it work for you?

**Comment by cbrocas** [comment]
Great answer! Particularly awaiting the point 2) ;-)
This solution is totally fine from my point of view!

**Comment by barkbay** [comment]
Just want to say Hi and thank you for Snuffleupagus

We are experimenting with it in some of our PHP 7 containers, I hope that one day we will be able to contribute.

As a colleague of @cbrocas  I apologize for the noise ;)

Enjoy the salt

**Comment by cbrocas** [comment]
@barkbay ;-) #neveralone

**Comment by jvoisin** [comment]
You can find our slides [here]( https://twitter.com/sp_php/status/1014868737143472129 ) and the video [here[( https://twitter.com/sp_php/status/1015167679966208001 ).
