### ISSUE TITLE
Samesite feature is broken with PHP 7.3

### ISSUE THREAD

**Issue by remicollet** [nbs-system/snuffleupagus#184]
the setcookie implementation in PHP 7.3+ now filter values for unwanted char.

Thus the hack to inject `"; samesite="` doesn't work anymore, a better solution is needed.

Possible way is to play with `sapi_header_op(SAPI_HEADER_REPLACE, ...)` but doesn't seems so easy

**Comment by remicollet** [comment]
See https://wiki.php.net/rfc/same-site-cookie which should allow to solve this issue nicely, but sadly, not yet implement in alpha2, the PR is still under discussion.

**Comment by jvoisin** [comment]
Yup, we're aware of this issue and decided to not support non-released HP versions, since they are changing too quickly.

But we'll be happy to help you if you decide to try to support it ♥

**Comment by jvoisin** [comment]
For the record, [this]( https://github.com/php/php-src/commit/5cb825df7251aeb28b297f071c35b227a3949f01 ) is the commit that broke our hack. Odds are that this attribute will be natively supported in PHP7.3, so the solution will likely to add compilation guards for PHP versions inferior to 7.3

**Comment by jvoisin** [comment]
SameSite [is supported]( https://wiki.php.net/rfc/same-site-cookie ) in PHP7.3

I think that we can simply wrap our code in an `#ifdef`, and show a warning to the user if they try to use our implementation with PHP > 7.2

**Comment by remicollet** [comment]
See PR #212    (this doesn't handles the array of options case)

**Comment by jvoisin** [comment]
Done in 1270bc0 thanks to the (amazing) @remicollet ♥
