### ISSUE TITLE
Reduce number of call to `get_complete_function_path`

### ISSUE THREAD

**Issue by xXx-caillou-xXx** [nbs-system/snuffleupagus#193]
We could save a bit of time by calling it in `sp_execute_ex` instead of `should_disable` and `should_drop_on_ret`.

**Comment by jvoisin** [comment]
Done in 7963580d72a358975133f86f01de2d2eab08ba38

**Comment by jvoisin** [comment]
Done in 050eefd845ed9a588a8c92ed10827b0669883145
