### ISSUE TITLE
Shall we kill CSRF with "samesite"?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#20]
The PHP people are expecting to [take a decision]( https://wiki.php.net/rfc/same-site-cookie ) regarding the support of the [samesite cookie attribute](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00). If they do agree, it **might** be included in php 7.3.

Currently, only Chrome (and Opera) [are supporting it]( https://caniuse.com/#feat=same-site-cookie-attribute ). There is also a five years old issue [opened at Mozilla]( https://bugzilla.mozilla.org/show_bug.cgi?id=795346 ) :/ No idea about [Edge]( https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17140412-support-samesite-cookie-option ).

Shall we *kinda-backport* [their patch ]( https://bugs.php.net/bug.php?id=72230 ) to snuffleupagus? 
For the record, php 7.2 will be supported until 2020

**Comment by buixor** [comment]
As we already have code for setting extra flags for cookies, why not :)

**Comment by jvoisin** [comment]
This was done in #71
