### ISSUE TITLE
debian packaging : follow debian compliance

### ISSUE THREAD

**Issue by ghurlus** [nbs-system/snuffleupagus#201]
Hello,

Your [Makefile]( https://github.com/nbs-system/snuffleupagus/blob/master/Makefile ) doesn't follow Debian compliance and I'm trying to improve that.

1. PECL / PEAR or just :
- I first started building a debian package using the debhelper [dh-php]( https://tracker.debian.org/pkg/dh-php ) and the makefile /usr/share/dh-php/pkg-pecl.mk, the latter greatly improving the build of a PECL package.
But this requires a different file hierarchy of this repo, for example https://salsa.debian.org/php-team/pecl/php-rrd
- It also requires a package.xml, which I failed to generate automatically https://pear.php.net/manual/en/guide.users.dependencytracking.generatingpackagexml.php
It finally requires that the package be prefixed by 'php-' : so we get the package php-snuffleupagus.
Check the gitlab debian repo to find many examples https://salsa.debian.org/php-team/ 
- most PECL packages use pkg-pecl.mk Makefile
- most PEAR packages use php-composer or 
```
%:
  dh --with phppear
``` 

Now I'm trying to build a package without these contraints, I should only be using dh-php and have this in the debian/rules:
```
%:
  dh --with php
```

2. git-buildpackage:
[git-buildpackage]( https://honk.sigxcpu.org/piki/projects/git-buildpackage/ ) (gbp) is the standard tool today to build a Debian package. I've already used it for other packages, but I'm still not expert at it.

**Comment by jvoisin** [comment]
Great!

Do you want us to change our files layout to be more PECL-compliant? We didn't bother with PECL, but if this can ease the Debian packaging we'll be more than happy to give it a try.

You mentioned that currently, our Makefile "doesn't follow Debian compliance", care to elaborate about this? Because except from a few warnings ( #140 ), I don't see what we're doing wrong :/

**Comment by ghurlus** [comment]
I eventually managed to not touch the file layout.

By Debian compliance I mean to better follow Debian Policy https://www.debian.org/doc/debian-policy/

For instance in your debian/changelog the version number X.Y.Z should be appended with a '-N' where N is the number of package release for the software release X.Y.Z
```
snuffleupagus (0.3.0-1)
```

For instance your debian/rules:
-  didn't use pkg-pecl.mk Makefile which helps in building a PHP extension, as a consequence Depends field content in the package was wrong
-  would only compile against the last PHP7 minor version installed when the resulting package should provide the .so file for each minor version

**Comment by jvoisin** [comment]
Any news on this front?

**Comment by ghurlus** [comment]
I'm still learning how to use git-buildpackage. For instance, compiling a new version is not as smooth as I expected.

**Comment by jvoisin** [comment]
Any news about this, or shall we close the issue?

**Comment by ghurlus** [comment]
Close the issue, I don't have time to work on it.
