### ISSUE TITLE
Session disk encryption

### ISSUE THREAD

**Issue by cypherbits** [nbs-system/snuffleupagus#205]
Hi, I see there is support for encrypted cookies but as I understand this is only on the client side. PHP stores the session files on a folder in plaintext, some CMS and PHP frameworks can encrypt this files but I think it will be better for performance to do it here in this extension.

A fast way to protect session files in PHP-FPM would be to generate a random password on every service start:

- **pros**: session files are encrypted, when you restart the service there is no way anyone can recover this data.
- **cons**: only works on php-fpm (no mod_php I think), sessions are lost when you restart the service so all users are logged out.

**Comment by kkadosh** [comment]
Hello @cypherbits ,

Thanks for your suggestion. It seems that there is a misunderstanding. We improved the
documentation to clarify how we're handling encryption of session cookies.
Can you please check it out, because it seems that we're already doing what you're suggesting

**Comment by cypherbits** [comment]
Ok, maybe it is because of the use of the word "cookie". Cookie is the "document" you send to the client, what PHP stores in the server are "session variables". Difference between what's on the server and the client is the key here...

What about the "random key" in sp.global.secret_key ? Can we have a new random key every time we restart php-fpm? This way the key is not stored on disk and is better for security of some websites.

**Comment by jvoisin** [comment]
The issue is that some people are running several php servers behind a single website. Using a random value would break load-balancing.

**Comment by cypherbits** [comment]
Ok, I close this thread then...
