### ISSUE TITLE
Add "ignore hash" feature in generate_rules.php script 

### ISSUE THREAD

**Issue by he2ss** [nbs-system/snuffleupagus#206]
Sometimes we need to generate rules without having file hash. If we can have a "ignore hash" feature that generate sames rules without file hash.

Also we need to update this variable `$functions_blacklist`, if you can add `function_exists` function in the list please.

**Comment by jvoisin** [comment]
In what case would you have a file name and no possible hash?

**Comment by buixor** [comment]
@jvoisin in case you know the code is going to evolve and you don't want to break production ?

**Comment by jvoisin** [comment]
I'd rather break the production and know about changes, than trusting the dev to not introduce glaring vulnerabilities. But I get your point.
