### ISSUE TITLE
URL-style protocols and wrappers

### ISSUE THREAD

**Issue by cypherbits** [nbs-system/snuffleupagus#209]
I saw this new vulnerability https://thehackernews.com/2018/08/php-deserialization-wordpress.html and I thought: I think most of the time developers don't use many of the wrappers available, why can't I disable them? Wrappers list: http://php.net/manual/en/wrappers.php

Is there a way right now to make a rule to disable all use of "phar://" "rar://" "ogg://" etc... ??

**Comment by jvoisin** [comment]
Done in #211
