### ISSUE TITLE
global simulation() mode

### ISSUE THREAD

**Issue by fr33tux** [nbs-system/snuffleupagus#22]
It would be nice to get a global simulation() to set all rules in simulation mode, instead of appending simulation() to each rule (which is a bit time-consuming and boring).

It may be an evolution to the current .ini format to set several rules in simulation at once - something like:

```python
## Rules in simulation() mode
sp.begin.simulation()
sp.disable_functions.function("chmod").param("mode").value_r("^[0-9]{2}[67]$").drop();
sp.disable_functions.function("chmod").param("mode").value_r("o\\+w$").drop();
sp.end.simulation()

sp.disable_functions.function_r("^(?:require|include)_once$").value_r("\\.(?:php|php7|inc|tpl)$").allow();
sp.disable_functions.function_r("^require|include$").value_r("\\.(?:php|php7|inc|tpl)$").allow();
sp.disable_functions.function_r("^(?:require|include)_once$").drop();
sp.disable_functions.function_r("^require|include$").drop();
```

The same principle could be extended to other actions (drop(), allow(), dump()).

(if it's not a good idea after all, feel free to close)

**Comment by jvoisin** [comment]
The only legitimate case for wanting to mark a batch of rules in simulation mode is when you're importing a bunch of rules for your CMS, and you're afraid that they might be badly written.

If it's the case (and you're using vim) you can define the `a` macro with this `qa$i.simulation()<esc>jq` and use it on your rules with `@a`, you can even repeat it by prefixing a number to its usage.

This isn't an operation that you should often do, and I'm reluctant to add more options to our configuration that has already [a lot]( https://snuffleupagus.readthedocs.io/config.html#filters ).

**Comment by fr33tux** [comment]
Makes sense, thanks!
