### ISSUE TITLE
Suggestions to improve the usability/usage of the logging system

### ISSUE THREAD

**Issue by crKontrol** [nbs-system/snuffleupagus#234]
Hello, 

Recently I faced an issue regarding the rules for hardening `rand()`. The feature was enabled and yes, it did break a website, but the problem is that nothing was logged. 

It will be good to have logs :) 

I see a few things that can be done :) :

- In the `phpfino()` we can have a list showing every feature enabled in the current configuration and we should see if the feature are in simulation mode or not. 

- This will be super cool to have a _boot log_ in php.log. Something like :
```
Snuffleupagus here !
Harden rand feature enable
etc...
```
The log should contains a list of all feature enabled and even more, for the whitelist stuff, the path to the file. And also, the version of Snuffleupagus installed and if is the latest. If not, we could a line telling us that we need to upgrade to the latest version.

- Level log :D - This one is an open question, because on my OPS point of view this will be marvelous but not for everyone. I think about 3 level log :
1) No log
2) Critical logs and warnings logs
3) Full logs -> yeah, this one must be a critical issue for disk space
For example, when we enable the harden rand feature and this is triggered, we have no logs and this is bothering me. I would love to know when one of Snuffleupagus feature is triggered this can help a lot for troubleshoot.

- The logs must be accessible from one and only log. Not something like, one piece in the web server logs, another on the syslog etc.. And again for my OPS point of view, I prefer to have it on the PHP logs or on a log dedicated to Snuffleupagus (like the one for suhosin).

**Comment by jvoisin** [comment]
- I like the idea of the `phpinfo` thingy, but I'm a bit afraid that this might leak juicy information to an attacker able to find a `phpinfo()` on, say, a `phpinfo.php` page.

- About the boot-log, why not, but is it really more convenient than reading your configuration file?

- For the log level, php [already provides this]( https://secure.php.net/manual/en/errorfunc.constants.php ). There is a `debug`-macro wrapper in Snuffleupagus' code (disabled by default) to help to, … well … debug, turned off by default. Maybe we could hide it in the `E_NOTICE` verbosity level of php.

- Snuffleupagus' is using php's logging system, there is nothing that we can do about this.

**Comment by crKontrol** [comment]
- If the `phpinfo()` is too sensible for exposing this data I can understand.

- For the boot-log, Yes this is usefull :) because it provide us a good view of what feature is enabled and the client can see it too since the php.log seems to be the only logs that Snuffleupagus is using :)

- Regarding the log level, that will be good to have a lot more advice I think. Did you test to use the php log level on this project yet ?

- As long as the logs are written on a single file, this is fine for us.

**Comment by jvoisin** [comment]
Feel free to do it, it shouldn't be that hard :)

**Comment by jvoisin** [comment]
@crKontrol Ping, are you planning to implement it?

**Comment by jvoisin** [comment]
@crKontrol Could you at least detail what you want to appear in the "boot-log"? I don't think that dumping the rules is wise, since odds are that some people have __a lot__ of them.

**Comment by jvoisin** [comment]
I have zero interest in implementing this feature; but feel free to re-open this issue if you want to work on it, or at least provide more details.
