### ISSUE TITLE
Task: fix travis configuration for 7.3

### ISSUE THREAD

**Issue by remicollet** [nbs-system/snuffleupagus#243]
Will be nice to have 7.3 in travis run.

**Comment by jvoisin** [comment]
Unfortunately, travis-ci doesn't provide PHP7.3 yet :/

**Comment by remicollet** [comment]
:(

And nightly is 7.4.0-dev :(

**Comment by jvoisin** [comment]
I know :'(

**Comment by jvoisin** [comment]
Done in 244f3da227d07b94602a3b517fcb8aefeb9f459d
