### ISSUE TITLE
Composer Being Blocked

### ISSUE THREAD

**Issue by cmachler** [nbs-system/snuffleupagus#258]
Hello,

We are trying to implement Snuffleupagus as a replacement to Suhosin in PHP 7, and are running into an issue when we run Composer. We are using the example configuration for Snuffleupagus from the documentation:

```python
PHP Fatal error:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists', because its argument '$function_name' content (proc_open) matched a rule in /usr/share/php/Composer/Package/Version/VersionGuesser.php on line 66
```

Is there an easy way to whitelist Composer in the configuration file?

Regards,

Chris

**Comment by jvoisin** [comment]
Something like this should do the job:

```python
sp.disable_function.function("function_exists").filename("/usr/share/php/Composer/Package/Version/VersionGuesser.php").allow();
```
