### ISSUE TITLE
Compile time mitigations

### ISSUE THREAD

**Issue by cypherbits** [nbs-system/snuffleupagus#262]
What about compile time mitigations? Is generic PHP already compiled with all GCC hardening flags? And the extensions? Can we use Clang ControlFlowIntegrity feature? New versions of GCC have more hardening features, should we enable them? make a tutorial for the best compile time hardening of php? 

These are just some questions I ask myself.

**Comment by jvoisin** [comment]
We're [already compiling]( https://github.com/nbs-system/snuffleupagus/blob/master/src/config.m4#L24 ) with hardening flags.

**Comment by jvoisin** [comment]
But do feel free to "play" with the `config.m4` file if you want to conditionally add some more ;)
