### ISSUE TITLE
It's currently not possible to hook builtins via regex

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#263]
We should either implement it, or document this as a limitation. I'm in favour of the second option, since:

- Most of the time, the user doesn't have to vpatch builtins
- Regex are slow
- The implementation looks non-trivial.

**Comment by xXx-caillou-xXx** [comment]
I don't think we should implement it. But people could try to match on `include.*` or `require.*`.

**Comment by jvoisin** [comment]
Then we should document this limitation ("you can't match builtins by regex"), and remove the dead code :)

**Comment by jvoisin** [comment]
Done in 54a24a61aadc9e33c3666a5d48ad1ac60e4178e6
