### ISSUE TITLE
Support "include" statement in the configuration file

### ISSUE THREAD

**Issue by fr33tux** [nbs-system/snuffleupagus#27]
It may be nice to provide a way to split the configuration file into multiple smaller ones.

A syntax like that `sp.include("file/to/import")` for instance.

**Comment by blotus** [comment]
This feature might be a bit too tricky to implement considering the overall usefulness, it would complicate  the configuration parsing code (which i find already too messy) for a not-so-great improvement.
I'm closing this for now, but i'm keeping the idea in the to-do list (and PR are always welcome :)).

**Comment by jvoisin** [comment]
Actually, we could use it via the `sp.configure_file` php directive: this wouldn't complexify the parsing, no need to deal with recursion and stuff like that, while still allowing include-like behaviour.
