### ISSUE TITLE
Slides mixed with code

### ISSUE THREAD

**Issue by szepeviktor** [nbs-system/snuffleupagus#276]
Please consider moving the slides.
e.g. to https://github.com/nbs-system/snuffleupagus-slides

**Comment by jvoisin** [comment]
I don't think that we want to rewrite the whole history of the project at this point, do we?

**Comment by szepeviktor** [comment]
rewrite the whole history? just move non-code files to a separate repo.

**Comment by szepeviktor** [comment]
What about a simple `git rm ...` ?

**Comment by jvoisin** [comment]
The slides would sill live in the history.
I thought that the whole point of removing the slides was to reduce the size of the repository. It isn't?

**Comment by jvoisin** [comment]
Mh, I don't see the correlation. Do you have some documentation about this? Shoving Snuffleupagus into PECL has been on my todo-list since a long time :)

**Comment by szepeviktor** [comment]
A PECL repo looks like this: https://github.com/phpredis/phpredis/

If you have slides for Snuffleupagus, no problem! You may have unlimited repos in GitHub.

**Comment by jvoisin** [comment]
The [pecl package for redis]( https://pecl.php.net/package/redis ) doesn't contain all the files from its git repository, so I guess there is a way to filter what goes into the archive and what doesn't.

Also, the name of the pecl package is `redis`, while the name of the repo is `phpredis`. An other counter-example is [libsodium-php]( https://github.com/jedisct1/libsodium-php ), packaged under the name [libsodium[( https://pecl.php.net/package/libsodium ).

**Comment by szepeviktor** [comment]
> so I guess there is a way to filter what goes into the archive and what doesn't.

Yes: https://github.com/phpredis/phpredis/blob/develop/package.xml#L77-L126

repo: snuffleupagus
PECL: snuffleupagus
Debian: php-snuffleupagus

**Comment by jvoisin** [comment]
So, what about:

1. Excluding the slides via the package.xml file
2. Decide what we want to do the next time we'll give a talk abut Snuffleupagus with regard to the slides' location?

**Comment by szepeviktor** [comment]
Okay!

I have client sticking their email signature in a folder of their website because they do not have an idea where else it can go.
