### ISSUE TITLE
new setcookie() signature from PHP 7.3 not supported

### ISSUE THREAD

**Issue by KiNgMaR** [nbs-system/snuffleupagus#287]
PHP 7.3 has added an "overload" of `setcookie` and `setrawcookie`:

```php
setcookie ( string $name [, string $value = "" [, array $options = [] ]] ) : bool
```

The implementation in PHP core looks expectedly funny:

https://github.com/php/php-src/blob/PHP-7.3/ext/standard/head.c#L253

This overload does no longer work if snuffleupagus is active, yielding `PHP Warning:  setcookie() expects parameter 3 to be int, array given`

Possible workaround in userland: use `setrawcookie($name, urlencode($value), $options);` instead.

I'll try to provide a patch for snuffleupagus. Should it also add hooking for `setrawcookie`?

**Comment by jvoisin** [comment]
I don't think it's worth hooking `setrawcookie`, since it's a "low level" interface.
I do look forward to review'n'merge your patch ♥

**Comment by KiNgMaR** [comment]
So I think there are two possible approaches to this.

The first one is to basically copy/paste the logic that extracts the settings (by key) from the array from PHP. As far as I can see, snuffleupagus uses LGPL, so copying PHP licensed code from PHP core should be okay. However all further changes to PHP core need to be replicated in snuffleupagus again.

The second one is to create a separate implementation of `sp_setcookie` for PHP 7.3+ that (after modifying the flags according to snuffleupagus' config) always call the original setcookie implementation (by means of `SNUFFLEUPAGUS_G(sp_internal_functions_hook)`).

Thoughts? :)

**Comment by jvoisin** [comment]
I think that the second approach is the best one, just use an `#ifdef` :)
(This also means that the day that we don't want to support anything below PHP7.3, we'll just have to remove the old implementation)

**Comment by jvoisin** [comment]
Done in 1cdb880fac5044194f0bc62dd82fcd4480192ebe
