### ISSUE TITLE
Support for php7.0 with 0.4.1

### ISSUE THREAD

**Issue by Yoda-BZH** [nbs-system/snuffleupagus#290]
Version: 0.4.1
Debian: stretch 9.8 (up to date)
PHP version: 7.0.33-0+deb9u1 (up to date)
Installed with the debian package hosted on github.

First, I had to create a symlink to install the library for php 7.0.
The package install the .so in /usr/lib/php/20180731/ only.
I suppose it's php7.3's directory.

Then, when I try to to anything in cli, I have an error related to libc6 :
```
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/snuffleupagus.so' - /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /usr/lib/php/20151012/snuffleupagus.so) in Unknown on line 0
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.24.4~linux-x64-non_zts70, https://blackfire.io, by Blackfire
```

I suppose the debian package is not linked against the debian version of libc6.

Hope this helps

Thank you !

Yoda-BZH

**Comment by jvoisin** [comment]
Unfortunately, I don't know much about Debian packaging, hence why the package is likely not working on your end. 

I guess you have to compile snuffleupagus by yourself via a `make debian` to produce a working Debian package :/

Feel free to send a pull-request if you know how to improve this ♥

**Comment by Yoda-BZH** [comment]
Hi

Compiling on my machine fixes the problem.

I suppose the .deb on github is not compiled on a debian stable/stretch, hence the glibc error.

If the glibc is dynamically linked, the package has to be compiled on every platform independently.

Compiling with the glibc statically could resolve the problem, but I don't think it's the right way.

**Comment by jvoisin** [comment]
yeah, I don't think it's the right way to go™
