### ISSUE TITLE
Config for bad parts of PHP

### ISSUE THREAD

**Issue by szepeviktor** [nbs-system/snuffleupagus#292]
extract() compact() list() etc. are your foes when writing clean OOP code

Could we develop a ruleset to strip bad parts off of PHP?

**Comment by jvoisin** [comment]
Why can't you use [disable_functions]( https://www.php.net/manual/en/ini.core.php#ini.disable-functions ) instead?

**Comment by szepeviktor** [comment]
Thank you!
