### ISSUE TITLE
compilation : make test does not work

### ISSUE THREAD

**Issue by ghurlus** [nbs-system/snuffleupagus#3]
See https://github.com/jvoisin/snuffleupagus/issues/333

**Comment by NattyNarwhal** [comment]
FWIW relevant to that issue, `make test` won't any other modules. You need to use `run-tests.php` and give it a command line that works, `TEST_PHP_ARGS="-d extension_dir=./modules -d extension=snuffleupagus" php run-tests.php` works for me (after copying system modules to modules, so extension_dir loads them there).
