### ISSUE TITLE
Shall we rename `disabled_function` to `virtual_patching` ?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#30]
@watw00t pointed out that `sp.disable_function.function("exec").filename("Cache/MySQL.php").hash("3c5e41[…]e8444cc").allow();` is a bit confusion, since we're not disabling anything, but are allowing a call to a function.

What about using `virtual_patching` or something like that instead?

**Comment by Kegeruneku** [comment]
Looks like a better naming indeed, much more POLA-compliant

**Comment by blotus** [comment]
I'm not a fan of this.
`disable_function` is used not only for virtual patching, but also for disabling functions :)

`sp.virtual_patching.function("system").drop()` does not make more sense.

Maybe we should add a separate `virtual_patching` keyword for virtual patching rules, and keep `disable_function` for disabling function ? (but the configuration and the code will probably get very messy very quick)

**Comment by jvoisin** [comment]
It does make sense: "virtual-patch the call to this function, by disabling it", and "virtual-patch the call to this function, it it matches this and that condition, by allowing it".

**Comment by buixor** [comment]
As it requires extra code and extra keyword support for`virtual_patching` to work, without adding any functionality, I suggest that we stick to `disabled_function`.

**Comment by jvoisin** [comment]
Maybe from `disable_functions` to `disable_function` at least?
