### ISSUE TITLE
Compilation warning - zend_auto_start declared static but never defined

### ISSUE THREAD

**Issue by fr33tux** [nbs-system/snuffleupagus#31]
Compiled using https://github.com/nbs-system/snuffleupagus/commit/1602780f3c85ca127c77d28ae93a4e2a4eeae180 with `make release`:

```
snuffleupagus/src/snuffleupagus.c:12:19: warning: ‘zend_auto_start’ declared ‘static’ but never defined [-Wunused-function]
 static inline int zend_auto_start(zend_extension *extension);
```

**Comment by jvoisin** [comment]
@blotus Shall we keep this in master, or move it to a branch for now?

**Comment by blotus** [comment]
We can move it to a branch for now, it was related to user functions hooking, but should not be needed anymore.

**Comment by jvoisin** [comment]
Be my guest then ♥
