### ISSUE TITLE
No more client IP in logging

### ISSUE THREAD

**Issue by kkadosh** [nbs-system/snuffleupagus#311]
Hi,

It seems that since #218, the client's ip isn't logged anymore.

Furthermore, it seems that we're using [`zend_error()`](https://github.com/nbs-system/snuffleupagus/blob/master/src/sp_utils.c#L33) in our logging subsystem, but this is not recommended according to [PHP's documentation]( https://wiki.php.net/internals/review_comments#don_t_use_zend_error ). Should we use the recommended function instead, a nice side effect would be that this should fix #306.

**Comment by wargio** [comment]
it's likely linked to the change from `php_log_err` (`_sp_log_err` uses that) to `zend_error`.

**Comment by jvoisin** [comment]
Wonderful idea, please proceed :)

**Comment by jvoisin** [comment]
done in b1a4af56f09a9469eeaf006480804451e60fe411.

Feel free to open an other issue for the `zend_error` → `php_error_docref` thingy.
