### ISSUE TITLE
Is it possible to disable a function, but allow a specific calling function to allow it?

### ISSUE THREAD

**Issue by tdondich** [nbs-system/snuffleupagus#315]
I want to disable the fopen function in general, however, I'd like to allow only a specific calling function such as some user defined function called secfopen, to allow it.  Can this be possible to disable a function, but whitelist calling functions to allow the disabled function to execute?

**Comment by jvoisin** [comment]
On 30/10/2019 19:23, tdondich wrote:
> I want to disable the fopen function in general, however, I'd like to
> allow only a specific calling function such as some user defined
> function called secfopen, to allow it.  Can this be possible to
> disable a function, but whitelist calling functions to allow the
> disabled function to execute?
> 

Absolutely, you can likely write something like this (untested):

```
sp.disable_function("secfopen>dangerous_function").allow();
sp.disable_function("dangerous_function").drop();
```
