### ISSUE TITLE
log request curl and file_get_contents

### ISSUE THREAD

**Issue by felipegabriel** [nbs-system/snuffleupagus#318]
Hello!
I wonder if it is possible to store the curl or file_get_contents logs or any ugly http request.

When an http request is made in PHP to store the address and post data,

if you can block certain addresses by blocking requests via curl or file_get_contents to certain IP or domain.

this to monitor hacked sites is interesting.

I'm already following the project and I thought it was very good.

sry  my English.

**Comment by jvoisin** [comment]
Sure, you can write some rules to impose addresses/urls to arbitrary functions like `file_get_contents`.
