### ISSUE TITLE
"Something went wrong with a regexp."

### ISSUE THREAD

**Issue by fr33tux** [nbs-system/snuffleupagus#35]
Using https://github.com/nbs-system/snuffleupagus/commit/b8dd5ce7f5d36c969944d425ff1fbe5f200a1dc8, I get this error testing against the https://github.com/nbs-system/snuffleupagus/blob/master/config/default.ini file.

Two points for this:
- It seems to be a bug somewhere,
- It would be great to actually get the actually rule which triggered this error from the *snuffleupagus.ini* config file.

Trying to catch where the error comes from is a bit annoying when the configuration file is ~200 rules..

**Comment by jvoisin** [comment]
Unfortunately, it's not possible to show the line, because the regexp thingy is used in a lot of places. I added some debug in 0e9086030f36f13a4007ae9e111fdcfbc40edbb1 to help you troubleshot the issue.

If I had to take a guess, I would say that it's likely due to a set of funky options in your PHP7.

**Comment by fr33tux** [comment]
> The default.ini file is tested in the testsuite, running on 3 different versions of PHP, and everything is green :/

Just to be clear, this error is logged at runtime and doesn't seem to make SP fails (I see rules catching requests as they should too).
The compilation is achieved without issue, and the test coverage doesn't show anymore failure than the current broken tests.

> If I had to take a guess, I would say that it's likely due to a set of funky options in your PHP7.
Server-side or compilation-side ?

**Comment by jvoisin** [comment]
My point was that we're running the `default.ini` file in php7.0, php7.1 and php7.2 without this warning poping up.

It seems that you have a PHP compiled with fancy options. Do you mind showing a `php -m`?

**Comment by fr33tux** [comment]
So, patching [sp_utils.c l358](https://github.com/nbs-system/snuffleupagus/blob/master/src/sp_utils.c#L363) show that `str` is not empty:

`+ sp_log_err("jvoisin jvoisin jvoisin", "value:%s:", str);`

Since https://github.com/nbs-system/snuffleupagus/commit/17f59cf9689e4a0d5d3c020eeb9a78c03f62e858 - ret = -2 is returned.

https://github.com/nbs-system/snuffleupagus/commit/9d284d6d8d489d231d20c8eef0035bdf01a2cbfe
Was maybe part of the problem, but it doesn't fix the issue.

`php -m` doesn't return anything unusual (confirmed with @jvoisin )

**Comment by jvoisin** [comment]
I can't manage to reproduce this behaviour :/
Apparently, this should be reproducible on a Debian Buster with gcc7.
Those messages are always appearing on certain requests, and sometimes when php is restarted.

**Comment by jvoisin** [comment]
@fr33tux you're using php-fpm, right?

**Comment by jvoisin** [comment]
We're not able to reproduce your issue :/

Is you issue present when you're commenting the `include/require/…` rules?

**Comment by fr33tux** [comment]
Everything is back to normal with https://github.com/nbs-system/snuffleupagus/commit/d875912a0528931c0828edfe30c37c01b559b761 \o/
