### ISSUE TITLE
Provide more information for phpinfo() output

### ISSUE THREAD

**Issue by buixor** [nbs-system/snuffleupagus#37]
Some extra information that might be worth displaying:

 - [ ] The version (and commit)
 - [ ] Whether the configuration was correctly parsed or not
 - [x] The path to the configuration file

**Comment by jvoisin** [comment]
Partially implemented in 472098193da5e03f7e96f7ed6a28525e5c8fd64d

**Comment by jvoisin** [comment]
Done in bf9218c.
