### ISSUE TITLE
Ensure invalid conf stops loading

### ISSUE THREAD

**Issue by buixor** [nbs-system/snuffleupagus#39]
Currently, even if the SP configuration is invalid, the php startup will continue (see `disabled_functions_param_invalid_pos.phpt` tests for example), but configuration parsing will be halted.

We need to make sure we fail to start to avoid invalid/broken configuration to go live.

**Comment by jvoisin** [comment]
Apparently, there is no (nice) way to prevent php from running when encountering a faulty configuration. We can either:
- Exit the process
- Crash
- Display a "Your sp config is broken, plz fix" page

**Comment by jvoisin** [comment]
@buixor proposed to display the error message in the `phpinfo()` call.

**Comment by buixor** [comment]
It won't **break** stuff, but it will make troubleshooting and support people life easier :)
