### ISSUE TITLE
Support filtering on functions with a variable number of arguments

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#4]
What about [printf](https://secure.php.net/manual/en/function.sprintf.php) who has this signature: `string sprintf ( string $format [, mixed $args [, mixed $... ]] )`? How can we virtual-patch the 2nd argument?

What about going with `.pos`, taking the position of the argument to considerate?

**Comment by buixor** [comment]
going with `.pos()` is OK, as long as you start index at 0 ! :)
