### ISSUE TITLE
Github releases have gone away?

### ISSUE THREAD

**Issue by drmuey** [nbs-system/snuffleupagus#4]
Hello,

We (cPAnel) use github releases to keep our snuffleupagus package up to date.

We notices recently that they have gone away (i.e. https://api.github.com/repos/nbs-system/snuffleupagus/releases is an empty array as is https://api.github.com/repos/nbs-system/snuffleupagus/tags).

Is there a reason for this? Any chance you can go back to github releases so we can stay up to date?

Thanks!

**Comment by jvoisin** [comment]
There is a new active upstream by one of the original authors: https://github.com/jvoisin/snuffleupagus/tags
See for yourself: https://github.com/nbs-system/snuffleupagus/graphs/contributors vs. https://github.com/jvoisin/snuffleupagus/graphs/contributors

**Comment by drmuey** [comment]
awesome thanks!
