### ISSUE TITLE
builtin_ssubl_overflow error during make

### ISSUE THREAD

**Issue by ljfreelancer88** [nbs-system/snuffleupagus#5]
When I compile using `make`, It compiled successfully, but I got the following error during compilation.
![Screenshot from 2022-03-03 10-09-09](https://user-images.githubusercontent.com/7919039/157050266-c4fec41d-6a24-46d5-ab24-ca6c38e150d0.png)

Thank you in advance.

**Comment by wargio** [comment]
os?

**Comment by wargio** [comment]
also, can you try with this repo https://github.com/jvoisin/snuffleupagus ?

**Comment by ljfreelancer88** [comment]
CentOS7. I used the jvoisin repo.

**Comment by wargio** [comment]
@jvoisin

**Comment by jvoisin** [comment]
That's not an error, bug a warning, and it looks unrelated to Snuffleupagus. Can you try to compile it again, but to remove the `CFLAGS=…` from the config.m4 file? Maybe your compiler doesn't like `-D_FORTIFY_SOURCE=2` or something.
