### ISSUE TITLE
Improve textual representation of zval to improve the '.dump' filter pertinence

### ISSUE THREAD

**Issue by buixor** [nbs-system/snuffleupagus#50]
`sp_convert_to_string`, used for getting a textual representation of zval should be improved, as it will impact `.dump()`'s pertinence :
- [ ] recursion on arrays
  - [ ] Handle circular references
- [ ]  At least object type for objects
  - [ ] Maybe something à la `var_dump`?

**Comment by jvoisin** [comment]
Duplicate of #42
