### ISSUE TITLE
Absolute file path in the `.filename` filter

### ISSUE THREAD

**Issue by xXx-caillou-xXx** [nbs-system/snuffleupagus#53]
Hi,
It would be great to have an error when the path of a file is not a full path, as it is not really specified in the doc (at least what I've read of it).

**Comment by sts** [comment]
Please add some docs as well, how is the path evaluated in respect to the document root? How would you structure the ruleset in case there are multiple vhosts, all hosting the same application?

**Comment by jvoisin** [comment]
The document root has nothing to do with the `.filename` filter. You can use a regexp if you have several vhosts.
