### ISSUE TITLE
sp.disable_xxe.enable(); removed?

### ISSUE THREAD

**Issue by felipegabriel** [nbs-system/snuffleupagus#6]
Default rules:
https://github.com/nbs-system/snuffleupagus/blob/master/config/default.rules

PHP error_log
PHP Fatal error:  [snuffleupagus][0.0.0.0][config][log] Unexpected keyword 'disable_xxe' on line 1 in Unknown on line 0

i have this problem, sp.disable_xxe.enable(); has been removed ?

**Comment by wargio** [comment]
please use the repo https://github.com/jvoisin/snuffleupagus and if you still have an issue with it, please open an issue into that repo.
