### ISSUE TITLE
Value in an array

### ISSUE THREAD

**Issue by xXx-caillou-xXx** [nbs-system/snuffleupagus#61]
Hi,
It would be great to be able to match a value in an array. Like using `.var("foo[bar][]")` to match any value in `$foo[bar]`'s array.

**Comment by jvoisin** [comment]
What about using a syntax like `arr_key` and `arr_value` to write things like:

- `.arr_key("arr[a]")` to match on a key contained in the sub-array `a` of the array `arr`
- `.arr_value("arr[a]")` to match on a value contained in the sub-array `a` of the array `arr`

**Comment by jvoisin** [comment]
Done in e7f541396715ee2895abcf73044b91ae9b746201
