### ISSUE TITLE
Improve cookie encryption

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#9]
This issue is based on the feedback from @nextgens, many thanks to him.

The cookie-jar encryption key is currently based on the IP of the user, its user-agent and a static secret key.

Assuming the user is using TLS, we should derive the *static-key* from  the extended master secret ([RFC7627](https://tools.ietf.org/html/rfc7627)), to make the encryption  TLS-session dependant rather than IP-dependant, with something like `key = hmac(global_secret, SSL_SESSION_ID);`. Worst case, we can always fallback to what we're currently using anyway.

In [Apache](https://httpd.apache.org/docs/current/mod/mod_ssl.html), it possible to access it with the `SSL_SESSION_ID` environment variable by adding `SSLOptions StdEnvVars` in the Apache2 configuration.

For nginx, the user has to set ` fastcgi_param SSL_SESSION_ID $ssl_session_id if_not_empty;`.

Using a static-key isn't a bad idea, but it should be possible to have a random one picked at startup (no configuration needed) ... and the option to specify one for those in clustered environments, because having a value the user has to set and no safe default will lead to bad defaults being picked, no matter how much we document it.

It would make sense to store it in a file, instead of using an hex-encoded secret, to improve proper randomness (people will be less likely to use `123123123123213213` as a secret if they have to write data in a file with `head -n 64 /dev/urandom > secret.key` as example in the doc.).
The file could be copy/pasted between different servers in a clustered environment.

**Comment by blotus** [comment]
I'm not sure that using the `SSL_SESSION_ID` is a good idea : 
 - It is transient, if the server or the client reboots, it's gone (but the same thing can be said about an IP address)
 - If the application is hosted behind a reverse proxy, all clients will share the same `SSL_SESSION_ID` as the ssl connection is negotiated between the RP and the web server
 - What about websites that don't use SSL ? (i know it's 2017, but i'll bet that the websites that need snuffleupagus the most don't use SSL)

**Comment by jvoisin** [comment]
People are less likely to  reset their TLS session than to move to an other IP thanks to roaming. For the reverse-proxy, we do have the same issue with our current IP-based approach: the server will see the IP of the RP, except if the users configures it properly, leading to point 3: we can always fallback to using our current solution :)

**Comment by blotus** [comment]
Except it is way easier to setup mod_rpaf so that the server will see the client IP than trying to forward the `SSL_SESSION_ID`  :)

**Comment by AshleyPinner** [comment]
Can I pop in a suggestion to let the system variable you look in for the IP be configurable? In our setup, since we're behind load balancers (with re-negotiated SSL), `REMOTE_ADDR` is the LB address. Thus in your setup, the IP address would have no variation between users.

**Comment by jvoisin** [comment]
This is done in 377cb2a15db578bc61f72c3f8d092599d7a44519

Thank everyone for the suggestions ♥
